# Use root/example as user/password credentials
version: "3.2"

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kmov1234
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

  express:
    build: ./server
    restart: always
    volumes:
      - ./server/:/app
      - /app/node_modules
    ports:
      - 5000:5000
    networks:
      - app-network
    depends_on:
      - mongodb

  client:
    build: ./client
    restart: always
    volumes:
      - ./client/:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - express
    stdin_open: true

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - client

networks:
  app-network:
    driver: bridge
