# Use root/example as user/password credentials
version: "3.2"

services:
  mongodb:
    image: mongo
    restart: "on-failure"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: kmov1234
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
  app:
    restart: "on-failure"
    build: ./client
    ports:
      - 80:80
  express:
    build: ./server
    ports:
      - 5000:5000
